/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.69
 * Generated at: 2016-04-24 17:51:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class signIn_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>SignIn Page </title>\r\n");
      out.write("<style>\r\n");
      out.write("\t\r\n");
      out.write("\tbody { background-color:#ffe6ff;}\r\n");
      out.write("\r\n");
      out.write("\th1 { text-align :center;}\r\n");
      out.write("\t.anchors{ \r\n");
      out.write("\t  \tfont-size:20pt; \r\n");
      out.write("\t  \ttext-decoration:none;\r\n");
      out.write("\t  \tcolor:blue;\r\n");
      out.write("\t  \tposition:relative;\r\n");
      out.write("\t  \tleft:40%;\r\n");
      out.write("\t }\r\n");
      out.write("\ta:visited { color: blue;} \r\n");
      out.write("\t.tables{\r\n");
      out.write("\t\tfont-size:15pt;\r\n");
      out.write("\t\tborder:1px solid;\r\n");
      out.write("\t\tpadding:20px;\r\n");
      out.write("\t\theight:250px;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t.submits{ font-size:13pt;background:#ffffcc;}\r\n");
      out.write("</style>\r\n");
      out.write("\t\r\n");
      out.write("<script>\r\n");
      out.write("function validate(){\r\n");
      out.write("\tif(myform.userId.value.trim() == null || myform.userId.value.trim() == \"\"){\r\n");
      out.write("\t\talert(\"Enter userid\");\r\n");
      out.write("\t}\r\n");
      out.write("\tif(myform.password.value.trim() == null|| myform.password.value.trim()==\"\" ){\r\n");
      out.write("\t\talert(\"Enter password\");\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<h1 style=\"font-family:Apple chancery;\">  EXPENSES ESTIMATOR </h1>\r\n");
      out.write("\r\n");
      out.write("\t\t<a href=\"signIn.jsp\" class=\"anchors\">Home</a>\r\n");
      out.write("\t\t&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t<a href=\"userForm.jsp\" class=\"anchors\"> Expenses Form</a>\r\n");
      out.write("\t\t<hr />\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<form name=\"myform\" method=\"post\" action=\"SignInPath\">\r\n");
      out.write("\t\t\t<h2 align=\"center\"> Sign In Form</h2>\r\n");
      out.write("\t\t\t<table class=\"tables\" align=\"center\" cellspacing=\"5\" cellpadding=\"10\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td align=\"right\">UserId: </td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" name=\"userId\" size=\"30\" /> </td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td align=\"right\">Password: </td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"password\" name=\"password\"  size=30/> </td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<td align=\"left\"><a href=\"signUpForm.jsp\" >SignUp ?</a></td>\r\n");
      out.write("\t\t\t\t\t<td align=\"center\"><input  class=\"submits\" type=\"submit\" onClick=\"validate()\"/></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
