/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.69
 * Generated at: 2016-04-24 06:08:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class userForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<?xml version=\"1.0\" encoding=\"ISO-8859-1\" ?>\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\" />\r\n");
      out.write("<title>User Details Form Page</title>\r\n");
      out.write("<style>\r\n");
      out.write("\t\r\n");
      out.write("\tbody { background-color:#ffe6ff;}\r\n");
      out.write("\r\n");
      out.write("\th1 { text-align :center;}\r\n");
      out.write("\t.anchors{ \r\n");
      out.write("\t  \tfont-size:20pt; \r\n");
      out.write("\t  \ttext-decoration:none;\r\n");
      out.write("\t  \tcolor:blue;\r\n");
      out.write("\t  \tposition:relative;\r\n");
      out.write("\t  \tleft:40%;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t }\r\n");
      out.write("\t \r\n");
      out.write("\t.tables{\r\n");
      out.write("\t\tfont-size:15pt;\r\n");
      out.write("\t\tborder:1px solid;\r\n");
      out.write("\t\tpadding:20px;\r\n");
      out.write("\t\theight:250px;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t.submits{ font-size:13pt;background:#ffffcc;}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\t\r\n");
      out.write("<script>\r\n");
      out.write("function validate()\r\n");
      out.write("{\r\n");
      out.write("\tif(myform.place.value.trim() == null || myform.place.value.trim() == \"\")\r\n");
      out.write("\t{\r\n");
      out.write("\t\talert(\"Enter Place of interest\");\r\n");
      out.write("\t\tmyform.place.focus();\r\n");
      out.write("\t}\r\n");
      out.write("\tif(myform.income.value.trim() == null|| myform.income.value.trim()==\"\" )\r\n");
      out.write("\t{\r\n");
      out.write("\t\talert(\"Enter Annual Income\");\r\n");
      out.write("\t\tmyform.income.focus();\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tif (myform.apt.selectedIndex == 0)\r\n");
      out.write("\t{\r\n");
      out.write("        alert(\"Please select a value from the Accommodation drop down.\");\r\n");
      out.write("        myform.apt.focus();\r\n");
      out.write("        \r\n");
      out.write("    }\r\n");
      out.write("\t\r\n");
      out.write("\tif (myform.transport.selectedIndex == 0)\r\n");
      out.write("\t{\r\n");
      out.write("        alert(\"Please select a value from the transport drop down.\");\r\n");
      out.write("        myform.transport.focus();\r\n");
      out.write("        \r\n");
      out.write("    }\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\t\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<h1 style=\"font-family:Apple chancery;\">  EXPENSES ESTIMATOR </h1>\r\n");
      out.write("\r\n");
      out.write("\t\t<a href=\"signIn.jsp\" class=\"anchors\">Home</a>\r\n");
      out.write("\t\t&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t<a href=\"userForm.jsp\" class=\"anchors\"> Expenses Form</a>\r\n");
      out.write("\t\t<hr />\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<form name=\"myform\" method=\"post\" action=\"signUpPath\" >\r\n");
      out.write("\t\t\t<h2 align=\"center\" \">User Expenses Form</h2>\r\n");
      out.write("\t\t\t<table class=\"tables\" align=\"center\" cellspacing=\"5\" cellpadding=\"10\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td align=\"right\">Place of Interest: </td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" name=\"place\" size=\"30\" /> </td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td align=\"right\">Annual Income: </td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" name=\"income\"  size=30/> </td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td align=\"right\">Accommodation Type: </td>\r\n");
      out.write("\t\t\t\t\t<td><select name=\"apt\" id=\"apt\" maxlength=\"40\">\r\n");
      out.write("\t\t\t\t\t\t<option selected > Select living style</option>\r\n");
      out.write("\t\t\t\t\t\t<option> 1 BH Apartment</option>\r\n");
      out.write("\t\t\t\t\t\t<option> 2 BH Apartment</option>\r\n");
      out.write("\t\t\t\t\t\t<option> 3 or more BH Apartment</option>\r\n");
      out.write("\t\t\t\t\t\t<option> 1 BH Individual House</option>\r\n");
      out.write("\t\t\t\t\t\t<option> 2 BH Individual House</option>\r\n");
      out.write("\t\t\t\t\t\t<option> 3 or more BH Individual House</option>\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td align=\"right\">Transport Type: </td>\r\n");
      out.write("\t\t\t\t\t<td><select name=\"transport\" id=\"transport\" maxlength=\"40\">\r\n");
      out.write("\t\t\t\t\t\t<option selected > Select transport type</option>\r\n");
      out.write("\t\t\t\t\t\t<option> train</option>\r\n");
      out.write("\t\t\t\t\t\t<option> car</option>\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t<td align=\"left\"><input  class=\"submits\" type=\"submit\"  onclick=\"validate()\" />\r\n");
      out.write("\t\t\t\t\t&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t<input  class=\"submits\" type=\"reset\" /></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
